#! /usr/bin/python3
import os

# Get current working directory and save it to variable as string
currentDir = str(os.getcwd())
os.system('clear')

def showHelp():
    """
    Show useful information about how to use the script
    """
    return """
            Sort is a simple program that lets you sort files into specific folders or archives based on their file extension

            Usage:

            Compress files of a specific extension into an archive
            sort -c <extension>

            Compress files at a specific directory into an archive
            sort -c <extension> <directory>
            

            Move files of a specific extension into a folder
            sort -f <extension>

            Move files of a specific extension on a specified directory into a folder
            sort -f <extension> <directory>
           """

def compressFiles(ext, dir):
    """
    Looks for files at the specified directory and then compresses
    the files into an archive.

    If the directory has not been specified then it'll default to
    using the current working directory
    """


def moveTo(ext, dir):
    """
    Looks for files at the specified directory and then moves them
    to a new folder that's named using the extension.
    """

    # Create a directory based on extension
    os.makedirs(dir.upper())
    sortingMsg(ext)

    # Move files to the directory
    os.system(f"mv -v ./*.{ext} ./{ext.upper()}")
    

def sortingMsg(ext):
    print(f"Sorting {ext} files...")


def getExt():
    """
    This function gets the extension of the files that you want to 
    work with
    """
    return str(input("Enter file extension: "))

moveTo("py", "~/lol")
